heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://es01:9200
    - http://kibana:5601
    - http://web:8080
    - http://nginx:80

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "http"

setup.kibana:
  host: "http://localhost:5601"
  protocol: "http"
  ssl.enabled: true
